= Lookup Table Library (LUT) Reference

NOTE: This is a reference documentation of the LUT library. See xref:README.adoc[] for usage documentation.

== `LUT`

The entry point object of this library. Instantiated when the program starts, so no need to create a new instance on your own.

=== Methods and Properties

==== `LUT.create(params)`

Creates a new lookup table object. `params` has the following fields:

[cols="1,1,4"]
|===

| Field | Type | Description

| name
| String
| Name of this lookup table

| ins
| String array
| Column titles of the in parameters

| outs
| String array
| Column titles of the out parameters
 
|===

==== `LUT.ANY`

A value matcher that matches any value.

==== `LUT.Range(min, max)`

Creates a matcher that matched an inclusive range, between `min` and `max`. When creating use cases from the LUT rows, a range matcher generates three cases: one for the minimum, one for the maximum, and one for a value in the middle of the range.

.Usage example
[source, javascript]
----
const r = LUT.Range(42, 76);
r.match(41) // false
r.match(42) // true
r.match(66) // true
r.match(76) // true
r.match(78) // false
----

==== `LUT.NoMatch`

A value returned by `lut.lookup(qry)` when no row matches the criteria posed by `qry`. False-ish, so can be used inside `if` statements.

==== `LUT.genBookStepHTML(event, testScenario)`

If the passed `event` is an event generated by a lookup table, adds proper tags and steps to the passed `testScenario`. Returns `true` if steps and tags were added, and `false` otherwise. The step description uses HTML. See xref:meta-spec/book-writer.js[] for a sample use.

==== `LUT.genBookStepXLS(event, testScenario)`

If the passed `event` is an event generated by a lookup table, adds proper tags and steps to the passed `testScenario`. Returns `true` if steps and tags were added, and `false` otherwise. The step description uses plain text only, so if fits the `qc-xls` format.


== `LookupTable`

This object represents a lookup table. It allows client to add rows, look values up, and generate use-case events.

== `name`

Name of the lookup table.

== `insTitles`

Titles for the _in_ columns.

== `outsTitles`

Titles for the _out_ columns.

== `rows`

An array holding the table rows.

== `addRow(row)`

Adds a new row to the table. The `row` parameter is an object that has the following fields:

[cols="1,1,4"]
|===

| Field | Type | Description

| ins
| Array or Object
| Contains the _in_ values for the row, that is the values that are be matched against when looking up out values. Can contain explicit values and general matchers, such as `LUT.ANY` and `LUT.Range`. Values may be specified as an array, or using object keys. See xref:spec.sample-recommendations.js[] for usage examples.

| outs
| Array or Object
| The values that will be looked up based on the values in the `ins` part of the row.

|===

== `lookup(query)`

Looks up a set of _out_ values, based on `query`, which is an array of values. The returned row is the first row whose values match those of `query`. Note that the row values may contain ranges and wildcards.
If a matching row is found, returns it `outs` object. This object contains the _outs_ matchers, which can be exact values, ranges, or wildcards. To get an actual value use `sampleValue()`. Matchers can be accessed by index of by name. See below code for example.

[source, javascript]
----
let expected = myLut.lookup(useCase.data.ins);
expected[0].sampleValue();     // access by index
expected.color.sampleValue()}; // access by name, assuming "color" is a field name
----


== `generateLutEvents`

Generates an array of use-cases, based on the _ins_ columns in the table rows. Each row generates at least one use-case. Rows with ranges generate more than a single case, to better cover the range they represent.

== `anyEvent`

An event set containing all events generated by this lookup table.